workflow debug

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -45,12 +45,16 @@ jobs:
           chmod -R 777 build
           chmod -R 777 Library
 
+          echo "Memory before build:"
+          free -h
+
           echo "$RUNNER_SUDO_PASSWORD" | sudo -S docker run --rm \
             -v "$(pwd):/project" \
             -v "$(pwd)/Unity_v6000.x.ulf:/project/Unity_v6000.x.ulf" \
             -w /project \
             -e UNITY_LICENSE_FILE=/project/Unity_v6000.x.ulf \
             $IMAGE \
+            unity-editor \
             -verbose \
             -batchmode \
             -nographics \
@@ -59,7 +63,11 @@ jobs:
             -manualLicenseFile /project/Unity_v6000.x.ulf \
             -projectPath . \
             -executeMethod Builder.BuildWebGL \
-            -logFile /dev/stdout
+            -logFile build.log
+
+          echo "Buid finished. Exit code: $?"
+          echo "Dumping logs:"
+          cat build.log || echo "Log file not found"
 
       - name: Fix Permissions
         if: always()
